name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Build Distribution
        run: |
          npm ci
          npm run build

      - name: Commit Changes
        run: |
          git config --global user.name 'ameddin73'
          git config --global user.email 'ameddin73@users.noreply.github.com'
          git commit -am "Automated report"
          git push